Change the library detection
Also removed some unnecessary things

diff --git a/application/package/linux/MultiMC b/application/package/linux/MultiMC
--- a/application/package/linux/MultiMC
+++ b/application/package/linux/MultiMC
@@ -29,7 +29,13 @@ export QT_PLUGIN_PATH="${MMC_DIR}/plugins"
 export QT_FONTPATH="${MMC_DIR}/fonts"
 
 # Detect missing dependencies...
-DEPS_LIST=`ldd "${MMC_DIR}"/plugins/*/*.so 2>/dev/null | grep "not found" | sort -u | awk -vORS=", " '{ print $1 }'`
+DEPS_LIST=""
+for dep in 'osspd' 'libopenal-dev'; do
+if ! dpkg -s $dep &>/dev/null; then
+#echo "$dep is missing!"
+DEPS_LIST+=$dep
+fi
+done
 if [ "x$DEPS_LIST" = "x" ]; then
     # We have all our dependencies. Run MultiMC.
     echo "No missing dependencies found."
@@ -40,56 +46,11 @@ if [ "x$DEPS_LIST" = "x" ]; then
     # Run MultiMC
     "${MMC_DIR}/bin/MultiMC" -d "${MMC_DIR}" "$@"
 
-    # Run MultiMC in valgrind
-    # valgrind --log-file="valgrind.log" --leak-check=full --track-origins=yes "${MMC_DIR}/bin/MultiMC" -d "${MMC_DIR}" "$@"
-
-    # Run MultiMC with callgrind, delay instrumentation
-    # valgrind --log-file="valgrind.log" --tool=callgrind --instr-atstart=no "${MMC_DIR}/bin/MultiMC" -d "${MMC_DIR}" "$@"
-    # use callgrind_control -i on/off to profile actions
-
     # Exit with MultiMC's exit code.
     exit $?
 else
-    # apt
-    if which apt-file &>/dev/null; then
-        LIBRARIES=`echo "$DEPS_LIST" | grep -oP "[^, ]*" | sort -u`
-        COMMAND_LIBS=`for LIBRARY in $LIBRARIES; do apt-file -l search $LIBRARY; done`
-        COMMAND_LIBS=`echo "$COMMAND_LIBS" | sort -u | awk -vORS=" " '{ print $1 }'`
-        INSTALL_CMD="sudo apt-get install $COMMAND_LIBS"
-    # pacman
-    elif which pkgfile &>/dev/null; then
-        LIBRARIES=`echo "$DEPS_LIST" | grep -oP "[^, ]*" | sort -u`
-        COMMAND_LIBS=`for LIBRARY in $LIBRARIES; do pkgfile $LIBRARY; done`
-        COMMAND_LIBS=`echo "$COMMAND_LIBS" | sort -u | awk -vORS=" " '{ print $1 }'`
-        INSTALL_CMD="sudo pacman -S $COMMAND_LIBS"
-    # dnf
-    elif which dnf &>/dev/null; then
-        LIBRARIES=`echo "$DEPS_LIST" | grep -oP "[^, ]*" | sort -u`
-        COMMAND_LIBS=`for LIBRARY in $LIBRARIES; do dnf whatprovides -q $LIBRARY; done`
-        COMMAND_LIBS=`echo "$COMMAND_LIBS" | grep -v 'Repo' | sort -u | awk -vORS=" " '{ print $1 }'`
-        INSTALL_CMD="sudo dnf install $COMMAND_LIBS"
-    # yum
-    elif which yum &>/dev/null; then
-        LIBRARIES=`echo "$DEPS_LIST" | grep -oP "[^, ]*" | sort -u`
-        COMMAND_LIBS=`for LIBRARY in $LIBRARIES; do yum whatprovides $LIBRARY; done`
-        COMMAND_LIBS=`echo "$COMMAND_LIBS" | sort -u | awk -vORS=" " '{ print $1 }'`
-        INSTALL_CMD="sudo yum install $COMMAND_LIBS"
-    # zypper
-    elif which zypper &>/dev/null; then
-        LIBRARIES=`echo "$DEPS_LIST" | grep -oP "[^, ]*" | sort -u`
-        COMMAND_LIBS=`for LIBRARY in $LIBRARIES; do zypper wp $LIBRARY; done`
-        COMMAND_LIBS=`echo "$COMMAND_LIBS" | sort -u | awk -vORS=" " '{ print $1 }'`
-        INSTALL_CMD="sudo zypper install $COMMAND_LIBS"
-    # emerge
-    elif which pfl &>/dev/null; then
-        LIBRARIES=`echo "$DEPS_LIST" | grep -oP "[^, ]*" | sort -u`
-        COMMAND_LIBS=`for LIBRARY in $LIBRARIES; do pfl $LIBRARY; done`
-        COMMAND_LIBS=`echo "$COMMAND_LIBS" | sort -u | awk -vORS=" " '{ print $1 }'`
-        INSTALL_CMD="sudo emerge $COMMAND_LIBS"
-    fi
 
-    MESSAGE="Error: MultiMC is missing the following libraries that it needs to work correctly:\n\t${DEPS_LIST}\nPlease install them from your distribution's package manager."
-    MESSAGE="$MESSAGE\n\nHint (please apply common sense): $INSTALL_CMD\n"
+    MESSAGE="Error: MultiMC/Minecraft is missing the following libraries that it needs to work correctly:\n\t${DEPS_LIST}\nPlease install them from your distribution's package manager."
 
     printerror "$MESSAGE"
     exit 1
